### PR TITLE
Add more text for Taskcluster

### PR DESCRIPTION
**Pull request by djmitche**
This splits the `description` into `summary` (on the project card) and `introduction` (on the project page).

I wrote an introduction for Taskcluster -- please edit it mercilessly /cc @helfi92!

I also did a very poor job of including the introduction in the project page -- it shows up as white-on-white text.  I'm happy to have advice about how to fix that, or I can land it as-is for fixing in a later PR.

### CODE REVIEW

**Comment by djmitche** [comment]
What sort of component?

**Comment by djmitche** [comment]
(I know nothing about material design..)

**Comment by fiennyangeln** [comment]
Oops Sorry! `<Typography> ... </Typography>`

**Comment by djmitche** [comment]
ok, updated to use `<Typography>`

**Comment by djmitche** [comment]
BTW probably a big blob of text at the top of the page isn't the best -- please feel free to make this fit your plan for the layout!

**Pull request merged**
