### PR TITLE
Fix wrong environment variables & typo in README

### PR DESCRIPTION
**Pull request by endiliey**
## Changes
1. Fix wrong `.env` referencing. It should be `GITHUB_PERSONAL_API_TOKEN`
2. Fix broken link to Mozilla Neutrino

## Test Plan
1. Run the website in dev & able to use GitHub GraphQL API :white_check_mark:
2. Check link working correctly :white_check_mark:

### CODE REVIEW

**Comment by helfi92** [comment]
Thanks for the pull-request @endiliey :) From https://github.com/mozilla-frontend-infra/codetribute/pull/30#discussion_r193745561, we decided to use `GITHUB_PERSONAL_API_TOKEN` to make it explicit that it's for accessing the API. To that end, `.neutrinorc` will need to be updated. Are you interested in sending a patch for that? Thanks again!

**Comment by endiliey** [comment]
@eliperelman done 🚀

**Comment by helfi92** [comment]
@eliperelman could you rename/create `GITHUB_PERSONAL_API_TOKEN` in Netlify, please? Once that's done, we can go ahead with the merge :)

**Comment by eliperelman** [comment]
@helfi92 done.

**Comment by helfi92** [comment]
Thanks Eli!

**Pull request merged**
