### PR TITLE
Create LICENSE

### LINKED ISSUE #400: No LICENSE file in main repository
Hello, I am a volunteer with the Wikimedia Foundation and we're planning to build something similar to what you folks have built here. We think it's a great solution. 

The front end stylesheets and javascript could be useful but there is no LICENSE document in the repository and I am unsure on how to proceed. Would be great if someone could look into it.

Thanks so much.

### PR DESCRIPTION
**Pull request by djmitche**
Fixes #400.

### CODE REVIEW

**Comment by djmitche** [comment]
is snyk hung?

**Comment by helfi92** [comment]
Looks like all checks are green.

**Comment by djmitche** [comment]
I can't click "merge" because I'm not a repo admin and it's waiting for snyk..

**Comment by helfi92** [comment]
Screen Shot 2020-07-28 at 8 44 27 AM

**Comment by djmitche** [comment]
image

**Comment by helfi92** [comment]
Can you click merge now? I made you an admin.

**Comment by djmitche** [comment]
with "As an administrator, you may still merge this pull request.", yes

**Pull request merged**
