### PR TITLE
filter out PRs from issue queries

### LINKED ISSUE #557: Rust project is not opened
Hi :)
When I enter the Rust project in codetribute, the Rust project is not opened.

Screenshot from 2022-04-07 01-04-33

URL) https://codetribute.mozilla.org/projects/rust

### PR DESCRIPTION
**Pull request by djmitche**
I'm not sure if there's a more appropriate way to filter these out in the graphql query, but this works!

Fixes #557.

### CODE REVIEW

**Comment by jcristau** [comment]
cc @mhoye

**Comment by djmitche** [comment]
@petemoore does your team still own codetribute?

**Review by petemoore — COMMENTED** [review]
I don't know who owns codetribute these days. :-/

I can rubber stamp, if you've been able to test locally etc, or if you could add a test that runs in the CI, that would be even better, just to be sure this doesn't break anything.

**Comment by petemoore** [comment]
I think this will get deployed to production on merge to main (via netlify), is that right?

**Comment by djmitche** [comment]
I believe that's correct -- or at least was correct.

I don't think codetribute has tests.  It's been a while, but I vaguely recall testing this.  At any rate, if it has an issue it's easy to back out.

**Review by lotas — APPROVED** [review]

**Comment by lotas** [comment]
Yay! I finally can merge those :)

**Pull request merged**
